-- GENERATED BY tool/make_seed.py — do not edit by hand.
-- Anchor: 2026-08-30 (four months ending in this one).
--
-- Synthetic data for the `dev` project ONLY (decision 17). It exists
-- so the three-month windows of H15, H17 and H18 and the reports of
-- H11 and H16 have something to show before four months of real use.
--
-- The dates below are literal on purpose: no current_date in SQL
-- (decision 7). They age, and re-anchoring is one command:
--     uv run tool/make_seed.py
--
-- Money is in CENTS and quantity in the smallest unit (decision B5).

begin;

-- Idempotent: rerunning replaces the same rows instead of piling up.
-- Purchases go first, because the catalog is what they reference.
delete from public.list_write_off;
delete from public.purchase_item;
delete from public.purchase;
delete from public.shopping_list_item;
delete from public.product;
delete from public.product_registration;
delete from public.product_type;
delete from public.brand;
delete from public.category;
delete from public.store;

-- Categories and types
insert into public.category (id, name) values ('c7b31039-8686-593c-b78d-a6a6a5656640', 'Bebidas');
insert into public.product_type (id, name, category_id, base_unit) values ('628708f7-dc4a-5e70-9098-187d8dcb6f67', 'Refrigerante', 'c7b31039-8686-593c-b78d-a6a6a5656640', 'milliliter');
insert into public.product_type (id, name, category_id, base_unit) values ('5fb9ef9e-c202-5703-8510-7bdcf4383669', 'Leite', 'c7b31039-8686-593c-b78d-a6a6a5656640', 'milliliter');
insert into public.category (id, name) values ('0f6cb4e4-8901-55df-b823-d2384d222eb6', 'Carnes');
insert into public.product_type (id, name, category_id, base_unit) values ('07a562ca-768a-591f-a251-b510546ec9fe', 'Acém', '0f6cb4e4-8901-55df-b823-d2384d222eb6', 'gram');
insert into public.category (id, name) values ('6725c95d-dbea-5be8-ab07-2a70ab456afd', 'Limpeza');
insert into public.product_type (id, name, category_id, base_unit) values ('c7d0add7-b080-5893-ba08-15193dd50027', 'Sabão em pó', '6725c95d-dbea-5be8-ab07-2a70ab456afd', 'gram');
insert into public.product_type (id, name, category_id, base_unit) values ('85b8c3a2-003a-541b-83f1-8f18aafa8168', 'Papel-alumínio', '6725c95d-dbea-5be8-ab07-2a70ab456afd', 'centimeter');
insert into public.category (id, name) values ('841aaa94-df62-51cb-8bb6-b3372bd34ebe', 'Hortifrúti');
insert into public.product_type (id, name, category_id, base_unit) values ('81aabfaa-bece-5012-bc61-6c84ab57a5c4', 'Banana', '841aaa94-df62-51cb-8bb6-b3372bd34ebe', 'gram');

-- Brands (a product with no brand keeps brand_id null — B2)
insert into public.brand (id, name) values ('de78b73f-0727-5183-9c6d-dc6c5a5bbc9f', 'Coca-Cola');
insert into public.brand (id, name) values ('274f6a3c-0939-5603-85e3-674c156ce530', 'Italac');
insert into public.brand (id, name) values ('03985986-a813-5574-8eb9-7c52fc054fe8', 'Omo');

-- Stores
insert into public.store (id, name) values ('fd74f421-6985-5a01-a45a-5f032a3f0adc', 'Supermercado Central');
insert into public.store (id, name) values ('8b85e087-52e6-5ebe-b460-b5f3c7af1254', 'Feira do Bairro');

-- Registrations and their leaves
insert into public.product_registration (id, product_type_id, brand_id, description, selling_mode) values ('ee29d2d1-278e-5bec-9bd0-3291bc1de3c1', '628708f7-dc4a-5e70-9098-187d8dcb6f67', 'de78b73f-0727-5183-9c6d-dc6c5a5bbc9f', '', 'by_piece');
insert into public.product (id, product_registration_id, piece_count, piece_size, piece_size_unit, total_content) values ('83a72a65-d3a4-5833-9cda-781bfb1edc8c', 'ee29d2d1-278e-5bec-9bd0-3291bc1de3c1', 1, 350, 'milliliter', 350);
insert into public.product (id, product_registration_id, piece_count, piece_size, piece_size_unit, total_content) values ('337b59b6-b90e-5752-813f-dacd6448362b', 'ee29d2d1-278e-5bec-9bd0-3291bc1de3c1', 6, 350, 'milliliter', 2100);
insert into public.product (id, product_registration_id, piece_count, piece_size, piece_size_unit, total_content) values ('9fa6005e-0d6c-5254-a7a1-54bf1074d89d', 'ee29d2d1-278e-5bec-9bd0-3291bc1de3c1', 1, 2000, 'milliliter', 2000);
insert into public.product (id, product_registration_id, piece_count, piece_size, piece_size_unit, total_content) values ('322c7e9d-527f-570a-84dd-2212f186bcc1', 'ee29d2d1-278e-5bec-9bd0-3291bc1de3c1', 1, 2500, 'milliliter', 2500);
insert into public.product_registration (id, product_type_id, brand_id, description, selling_mode) values ('9a8ffdf9-bb94-5663-b658-fbfec7856407', '07a562ca-768a-591f-a251-b510546ec9fe', null, 'moído', 'by_weight');
insert into public.product (id, product_registration_id) values ('7bc452ba-720a-513c-ba02-2199adaba320', '9a8ffdf9-bb94-5663-b658-fbfec7856407');
insert into public.product_registration (id, product_type_id, brand_id, description, selling_mode) values ('bcd4deb8-4ad1-5932-8f76-3e1d74fe0615', '5fb9ef9e-c202-5703-8510-7bdcf4383669', '274f6a3c-0939-5603-85e3-674c156ce530', 'integral', 'by_piece');
insert into public.product (id, product_registration_id, piece_count, piece_size, piece_size_unit, total_content) values ('80558651-aaf5-587e-9f6b-e9f065a44c02', 'bcd4deb8-4ad1-5932-8f76-3e1d74fe0615', 1, 1000, 'milliliter', 1000);
insert into public.product_registration (id, product_type_id, brand_id, description, selling_mode) values ('3ed9bbe9-ef36-505a-81c3-418122ef69f3', 'c7d0add7-b080-5893-ba08-15193dd50027', '03985986-a813-5574-8eb9-7c52fc054fe8', '', 'by_piece');
insert into public.product (id, product_registration_id, piece_count, piece_size, piece_size_unit, total_content) values ('c3f201f9-20be-5c2f-bf36-822617c62400', '3ed9bbe9-ef36-505a-81c3-418122ef69f3', 1, 800, 'gram', 800);
insert into public.product_registration (id, product_type_id, brand_id, description, selling_mode) values ('af92f9e1-5a0e-5b1b-a9f2-0adb20e61dc2', '85b8c3a2-003a-541b-83f1-8f18aafa8168', null, '', 'by_piece');
insert into public.product (id, product_registration_id, piece_count, piece_size, piece_size_unit, total_content) values ('64c8c659-5f45-55b0-a36d-9a17f64501b8', 'af92f9e1-5a0e-5b1b-a9f2-0adb20e61dc2', 1, 3000, 'centimeter', 3000);
insert into public.product_registration (id, product_type_id, brand_id, description, selling_mode) values ('85434786-29c6-5353-9760-fcb55fd26c3c', '81aabfaa-bece-5012-bc61-6c84ab57a5c4', null, 'prata', 'by_weight');
insert into public.product (id, product_registration_id) values ('7eb2aa73-26a4-5996-aa0a-6245956c6ac4', '85434786-29c6-5353-9760-fcb55fd26c3c');

-- 8 purchases over four months, alternating store and buyer.
-- Prices rise from 2026-07-01 on, so H15 has an increase to find.
insert into public.purchase (id, purchase_date, store_id, registered_by) values ('f41928a6-7cfd-5e19-a4ab-a6b51559fcd8', '2026-05-05', 'fd74f421-6985-5a01-a45a-5f032a3f0adc', 'Leandro');
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('ff5d85ea-f81d-5560-a5c3-23ebda665ac8', 'f41928a6-7cfd-5e19-a4ab-a6b51559fcd8', '83a72a65-d3a4-5833-9cda-781bfb1edc8c', 1, 350, 349);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('49bb5138-43dc-52f3-ab19-b4c38972a272', 'f41928a6-7cfd-5e19-a4ab-a6b51559fcd8', '7bc452ba-720a-513c-ba02-2199adaba320', 1000, 1000, 3290);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('9843499c-8768-59d2-a63a-7fe6ec48ed34', 'f41928a6-7cfd-5e19-a4ab-a6b51559fcd8', '80558651-aaf5-587e-9f6b-e9f065a44c02', 1, 1000, 529);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('588d39e4-bc5b-5570-b28f-781626814695', 'f41928a6-7cfd-5e19-a4ab-a6b51559fcd8', 'c3f201f9-20be-5c2f-bf36-822617c62400', 1, 800, 1890);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('feef91be-a9ff-543e-a056-95513d01237c', 'f41928a6-7cfd-5e19-a4ab-a6b51559fcd8', '64c8c659-5f45-55b0-a36d-9a17f64501b8', 1, 3000, 1290);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('76010432-0f12-5a3e-81b4-c77f89b1bc39', 'f41928a6-7cfd-5e19-a4ab-a6b51559fcd8', '7eb2aa73-26a4-5996-aa0a-6245956c6ac4', 1000, 1000, 749);

insert into public.purchase (id, purchase_date, store_id, registered_by) values ('57f3746c-d320-519b-a995-bb6be1362556', '2026-05-19', '8b85e087-52e6-5ebe-b460-b5f3c7af1254', 'Esposa');
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('da152796-4a24-54fb-a041-a73ecfcf440b', '57f3746c-d320-519b-a995-bb6be1362556', '322c7e9d-527f-570a-84dd-2212f186bcc1', 2, 5000, 2380);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('24290c4d-4059-5193-bd1a-42fc3fa8c5bb', '57f3746c-d320-519b-a995-bb6be1362556', '7bc452ba-720a-513c-ba02-2199adaba320', 1200, 1200, 3588);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('9e55799b-c4f0-5d90-8116-44979dd979f1', '57f3746c-d320-519b-a995-bb6be1362556', '80558651-aaf5-587e-9f6b-e9f065a44c02', 2, 2000, 1118);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('4e5c03e8-a30d-569d-a76d-54ba6f4b593b', '57f3746c-d320-519b-a995-bb6be1362556', 'c3f201f9-20be-5c2f-bf36-822617c62400', 2, 1600, 3980);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('9e07bd77-dfc0-57d4-b3a3-1e644abfb407', '57f3746c-d320-519b-a995-bb6be1362556', '64c8c659-5f45-55b0-a36d-9a17f64501b8', 2, 6000, 2780);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('95b99e8d-c861-5e03-8bf1-fcd269997fd6', '57f3746c-d320-519b-a995-bb6be1362556', '7eb2aa73-26a4-5996-aa0a-6245956c6ac4', 1200, 1200, 718);

insert into public.purchase (id, purchase_date, store_id, registered_by) values ('469e43ff-855f-5016-9aaa-68c0c9195cd4', '2026-06-05', 'fd74f421-6985-5a01-a45a-5f032a3f0adc', 'Leandro');
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('6aa5c780-5220-5168-a5ac-5e1c0a1dee11', '469e43ff-855f-5016-9aaa-68c0c9195cd4', '9fa6005e-0d6c-5254-a7a1-54bf1074d89d', 1, 2000, 899);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('f94d8602-c3ff-5620-8f8a-e7a1efeedadb', '469e43ff-855f-5016-9aaa-68c0c9195cd4', '7bc452ba-720a-513c-ba02-2199adaba320', 1400, 1400, 4606);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('4675b125-4719-5df9-af04-432b83ac16c5', '469e43ff-855f-5016-9aaa-68c0c9195cd4', '80558651-aaf5-587e-9f6b-e9f065a44c02', 1, 1000, 529);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('082ba4d9-2426-57cc-b857-6f6b31307d83', '469e43ff-855f-5016-9aaa-68c0c9195cd4', 'c3f201f9-20be-5c2f-bf36-822617c62400', 1, 800, 1890);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('b426ed72-c7de-53ee-b0a3-6861d0ccf983', '469e43ff-855f-5016-9aaa-68c0c9195cd4', '64c8c659-5f45-55b0-a36d-9a17f64501b8', 1, 3000, 1290);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('1cae6bcf-40c1-555c-913b-467a2bc226ba', '469e43ff-855f-5016-9aaa-68c0c9195cd4', '7eb2aa73-26a4-5996-aa0a-6245956c6ac4', 1400, 1400, 1048);

insert into public.purchase (id, purchase_date, store_id, registered_by) values ('ef538d58-5d64-5157-8d8b-300e79182e39', '2026-06-19', '8b85e087-52e6-5ebe-b460-b5f3c7af1254', 'Esposa');
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('3cf6c6d1-b56e-5e72-8dac-69b88355df8a', 'ef538d58-5d64-5157-8d8b-300e79182e39', '337b59b6-b90e-5752-813f-dacd6448362b', 2, 4200, 4180);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('3c2f4550-ffe1-5ea5-b4c2-b0bdb5b9354c', 'ef538d58-5d64-5157-8d8b-300e79182e39', '7bc452ba-720a-513c-ba02-2199adaba320', 1000, 1000, 2990);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('7ff81d95-efe0-520c-b07c-5e02b3b9a93a', 'ef538d58-5d64-5157-8d8b-300e79182e39', '80558651-aaf5-587e-9f6b-e9f065a44c02', 2, 2000, 1118);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('f8716522-2687-5e9b-aad6-d686a0d57312', 'ef538d58-5d64-5157-8d8b-300e79182e39', 'c3f201f9-20be-5c2f-bf36-822617c62400', 2, 1600, 3980);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('8c0ad06a-8d79-5bfb-b0fd-431227bb8c35', 'ef538d58-5d64-5157-8d8b-300e79182e39', '64c8c659-5f45-55b0-a36d-9a17f64501b8', 2, 6000, 2780);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('82f7851d-2e70-5827-9173-1fd10302795f', 'ef538d58-5d64-5157-8d8b-300e79182e39', '7eb2aa73-26a4-5996-aa0a-6245956c6ac4', 1000, 1000, 599);

insert into public.purchase (id, purchase_date, store_id, registered_by) values ('188e9890-e404-529b-9801-0221dcf92af1', '2026-07-05', 'fd74f421-6985-5a01-a45a-5f032a3f0adc', 'Leandro');
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('d1599374-b209-577a-948d-6164f0a2cc04', '188e9890-e404-529b-9801-0221dcf92af1', '83a72a65-d3a4-5833-9cda-781bfb1edc8c', 1, 350, 529);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('9ef7ffb0-bf49-54e8-a924-52c64df7e238', '188e9890-e404-529b-9801-0221dcf92af1', '7bc452ba-720a-513c-ba02-2199adaba320', 1200, 1200, 3948);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('a60d9ee8-027c-59d6-b7fb-f95613e873ae', '188e9890-e404-529b-9801-0221dcf92af1', '80558651-aaf5-587e-9f6b-e9f065a44c02', 1, 1000, 529);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('9d76432b-2e6b-5e10-b595-279cab1ae3e4', '188e9890-e404-529b-9801-0221dcf92af1', 'c3f201f9-20be-5c2f-bf36-822617c62400', 1, 800, 1890);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('b9b7396d-4d15-553c-a603-9b4260645a47', '188e9890-e404-529b-9801-0221dcf92af1', '64c8c659-5f45-55b0-a36d-9a17f64501b8', 1, 3000, 1290);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('c34c5442-f592-5618-8c0d-0525272047d2', '188e9890-e404-529b-9801-0221dcf92af1', '7eb2aa73-26a4-5996-aa0a-6245956c6ac4', 1200, 1200, 898);

insert into public.purchase (id, purchase_date, store_id, registered_by) values ('f76128b5-d608-5ac3-8098-95369a702347', '2026-07-19', '8b85e087-52e6-5ebe-b460-b5f3c7af1254', 'Esposa');
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('73a26430-f5bc-5c4c-9e18-93d4058064ec', 'f76128b5-d608-5ac3-8098-95369a702347', '322c7e9d-527f-570a-84dd-2212f186bcc1', 2, 5000, 2740);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('b1eb77f6-79be-5105-a971-ca579c413c65', 'f76128b5-d608-5ac3-8098-95369a702347', '7bc452ba-720a-513c-ba02-2199adaba320', 1400, 1400, 4186);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('fa99865a-1824-59f6-9bc7-406845b3a1e5', 'f76128b5-d608-5ac3-8098-95369a702347', '80558651-aaf5-587e-9f6b-e9f065a44c02', 2, 2000, 1118);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('b5d990d3-aacd-51e5-b046-bbff35d2a09d', 'f76128b5-d608-5ac3-8098-95369a702347', 'c3f201f9-20be-5c2f-bf36-822617c62400', 2, 1600, 3980);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('14caa605-f01a-52cb-a5ab-486722e6ae37', 'f76128b5-d608-5ac3-8098-95369a702347', '64c8c659-5f45-55b0-a36d-9a17f64501b8', 2, 6000, 2780);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('80e5c590-bded-57a4-a842-a524635619bc', 'f76128b5-d608-5ac3-8098-95369a702347', '7eb2aa73-26a4-5996-aa0a-6245956c6ac4', 1400, 1400, 838);

insert into public.purchase (id, purchase_date, store_id, registered_by) values ('883390c0-298c-5050-b4af-75891ddc0b5d', '2026-08-05', 'fd74f421-6985-5a01-a45a-5f032a3f0adc', 'Leandro');
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('94305e9f-2a0a-5852-a4cf-0de92e4b7385', '883390c0-298c-5050-b4af-75891ddc0b5d', '9fa6005e-0d6c-5254-a7a1-54bf1074d89d', 1, 2000, 1079);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('3872f704-8fa2-559d-a56e-b3030ad02d95', '883390c0-298c-5050-b4af-75891ddc0b5d', '7bc452ba-720a-513c-ba02-2199adaba320', 1000, 1000, 3290);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('e4cf1ca1-8aac-5152-98eb-8914d8c112d0', '883390c0-298c-5050-b4af-75891ddc0b5d', '80558651-aaf5-587e-9f6b-e9f065a44c02', 1, 1000, 529);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('4eb8653d-b39e-55c0-b791-5a1c5b90d8f6', '883390c0-298c-5050-b4af-75891ddc0b5d', 'c3f201f9-20be-5c2f-bf36-822617c62400', 1, 800, 1890);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('8e444612-3e83-5cb2-b910-a97688f58b52', '883390c0-298c-5050-b4af-75891ddc0b5d', '64c8c659-5f45-55b0-a36d-9a17f64501b8', 1, 3000, 1290);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('d9b361c9-ca8e-515a-9913-6b606d7386aa', '883390c0-298c-5050-b4af-75891ddc0b5d', '7eb2aa73-26a4-5996-aa0a-6245956c6ac4', 1000, 1000, 749);

insert into public.purchase (id, purchase_date, store_id, registered_by) values ('e4a5b064-3935-51e1-baa6-e8e25ddec6aa', '2026-08-19', '8b85e087-52e6-5ebe-b460-b5f3c7af1254', 'Esposa');
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('5089195e-b308-549b-8872-a5302a203fdd', 'e4a5b064-3935-51e1-baa6-e8e25ddec6aa', '337b59b6-b90e-5752-813f-dacd6448362b', 2, 4200, 4540);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('f402d1e1-5cf4-5229-af00-59d2e9dfb8c2', 'e4a5b064-3935-51e1-baa6-e8e25ddec6aa', '7bc452ba-720a-513c-ba02-2199adaba320', 1200, 1200, 3588);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('f9533ac9-7833-5ea5-91ac-4359708e9647', 'e4a5b064-3935-51e1-baa6-e8e25ddec6aa', '80558651-aaf5-587e-9f6b-e9f065a44c02', 2, 2000, 1118);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('f63d9082-5a93-588b-98f4-0843483b1cb1', 'e4a5b064-3935-51e1-baa6-e8e25ddec6aa', 'c3f201f9-20be-5c2f-bf36-822617c62400', 2, 1600, 3980);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('f65f0062-e68f-5a6a-bcd1-de42415b6480', 'e4a5b064-3935-51e1-baa6-e8e25ddec6aa', '64c8c659-5f45-55b0-a36d-9a17f64501b8', 2, 6000, 2780);
insert into public.purchase_item (id, purchase_id, product_id, quantity, quantity_in_base_unit, total_paid) values ('e72490a4-dd5d-55f5-b34e-e33c85bb0414', 'e4a5b064-3935-51e1-baa6-e8e25ddec6aa', '7eb2aa73-26a4-5996-aa0a-6245956c6ac4', 1200, 1200, 718);

-- A shopping list with something already on it
insert into public.shopping_list_item (id, product_type_id, preferred_brand_id, preferred_product_id, quantity, entered_on) values ('41040cbb-8ec3-5517-a546-5521ed714406', '5fb9ef9e-c202-5703-8510-7bdcf4383669', '274f6a3c-0939-5603-85e3-674c156ce530', '80558651-aaf5-587e-9f6b-e9f065a44c02', 6000, '2026-08-30');
insert into public.shopping_list_item (id, product_type_id, preferred_brand_id, preferred_product_id, quantity, entered_on) values ('576ce940-f0b2-54c0-9f75-d2730aec5cf5', '628708f7-dc4a-5e70-9098-187d8dcb6f67', 'de78b73f-0727-5183-9c6d-dc6c5a5bbc9f', null, 3000, '2026-08-29');
insert into public.shopping_list_item (id, product_type_id, preferred_brand_id, preferred_product_id, quantity, entered_on) values ('e480a027-6980-5136-a474-b9144531e416', '81aabfaa-bece-5012-bc61-6c84ab57a5c4', null, null, 1500, '2026-08-28');
insert into public.shopping_list_item (id, product_type_id, preferred_brand_id, preferred_product_id, quantity, entered_on) values ('39d40e0c-1c10-5f50-b63e-d42321c8b0fd', 'c7d0add7-b080-5893-ba08-15193dd50027', null, null, null, '2026-08-27');

-- H9: a list item CLOSED by a purchase, with its trail
insert into public.shopping_list_item (id, product_type_id, quantity, entered_on, fulfilled_on) values ('b2ba94f8-0ecf-5e29-bf0e-037dced1b576', '07a562ca-768a-591f-a251-b510546ec9fe', 1000, '2026-05-01', '2026-08-19');
insert into public.list_write_off (purchase_item_id, shopping_list_item_id, quantity_written_off, cleared_not_found) values ('f402d1e1-5cf4-5229-af00-59d2e9dfb8c2', 'b2ba94f8-0ecf-5e29-bf0e-037dced1b576', 1000, true);

-- H9: a PARTIAL write-off — 6 L asked, part bought, still on the list
insert into public.shopping_list_item (id, product_type_id, quantity, entered_on) values ('be8fd7e8-2e4c-53ba-a2fa-dd479ffcdaf6', '5fb9ef9e-c202-5703-8510-7bdcf4383669', 6000, '2026-05-01');
insert into public.list_write_off (purchase_item_id, shopping_list_item_id, quantity_written_off, cleared_not_found) values ('f9533ac9-7833-5ea5-91ac-4359708e9647', 'be8fd7e8-2e4c-53ba-a2fa-dd479ffcdaf6', 2000, false);

-- H10: one deactivated row of each of the six catalogs
insert into public.category (id, name, active) values ('086f7639-9e9e-52e4-a624-5d676e565500', 'Padaria', false);
insert into public.product_type (id, name, category_id, base_unit, active) values ('69c32a80-2264-53bf-99b0-541e6248b251', 'Iogurte', 'c7b31039-8686-593c-b78d-a6a6a5656640', 'milliliter', false);
insert into public.brand (id, name, active) values ('3326ed0d-6943-51f3-9b28-8f739230c71c', 'Marca Antiga', false);
insert into public.product_registration (id, product_type_id, brand_id, description, selling_mode, active) values ('6e5b4af4-5680-580b-b96d-397a1d724b1e', '5fb9ef9e-c202-5703-8510-7bdcf4383669', null, 'desnatado', 'by_piece', false);
insert into public.product (id, product_registration_id, piece_count, piece_size, piece_size_unit, total_content) values ('cae7b229-b91d-5533-8081-c5281b75b490', '6e5b4af4-5680-580b-b96d-397a1d724b1e', 1, 1000, 'milliliter', 1000);
-- A leaf deactivated on its own, under an ACTIVE registration (decision 23):
insert into public.product (id, product_registration_id, piece_count, piece_size, piece_size_unit, total_content, active) values ('8f529db0-e7cb-5605-94af-30c17133a7eb', 'ee29d2d1-278e-5bec-9bd0-3291bc1de3c1', 1, 1500, 'milliliter', 1500, false);
insert into public.store (id, name, active) values ('819e0103-1d80-55f4-a581-8f934c04f282', 'Mercearia do Zé', false);

-- H13: the cap in force, and the 80% of this month already given
insert into public.spending_cap (id, amount, effective_from) values ('f3800515-63e6-5502-8b14-017ca9855ab1', 150000, '2026-05-01');
insert into public.spending_cap_alert (id, month, warned_80_at) values ('b557c4ef-ec10-5943-b15e-345c4b577bff', '2026-08-01', '2026-08-01');

commit;
