# /// script
# requires-python = ">=3.12"
# dependencies = []
# ///
"""Generates `supabase/catalog_import.sql`: the catalog of `seed_catalog.md` for `prod`.

    uv run tool/import_catalog.py
    psql ... -v ON_ERROR_STOP=1 -f supabase/catalog_import.sql

**Unlike `make_seed.py`, this one ADDS and never deletes.** `prod` has real
purchases pointing at its catalog, so every insert is guarded by a "not
exists" over the NORMALIZED name — the same comparison as the unique indexes —
and rerunning the file changes nothing the second time.

The `CATEGORY_RENAMES`, `TYPE_CHANGES` and `DEACTIVATED_CATEGORIES` below are
the one-off reconciliation of the rows `prod` already had, decided by the user
one by one on 28/09/2026. They run BEFORE the inserts, so a renamed row is
found by the insert and reused instead of duplicated.
"""

from __future__ import annotations

import importlib.util
import sys
from dataclasses import dataclass
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "supabase" / "catalog_import.sql"

# The parser lives in make_seed.py; loading it by path keeps one reader of the
# Markdown instead of two that drift apart.
_spec = importlib.util.spec_from_file_location("make_seed", ROOT / "tool" / "make_seed.py")
assert _spec and _spec.loader
make_seed = importlib.util.module_from_spec(_spec)
# dataclasses looks the module up by name while building the classes.
sys.modules["make_seed"] = make_seed
_spec.loader.exec_module(make_seed)


# Existing category name -> catalog category name.
CATEGORY_RENAMES = {
    "Fruta": "Frutas",
    "Frios e laticínios": "Frios, laticínios",
    "Biscoitos": "Biscoitos e snacks",
    "Enlatado": "Enlatados e instantâneos",
    "Higiene": "Higiene e beleza",
    "Merc seca": "Grãos e massas",
    "Molho e extrato": "Óleos, temperos e molhos",
}


@dataclass(frozen=True)
class TypeChange:
    """What happens to one existing type. `None` keeps the current value."""

    current: str
    name: str | None = None
    category: str | None = None
    base_unit: str | None = None


TYPE_CHANGES = [
    # The three types of "açogue", split by animal.
    TypeChange("carne bovina", name="Carne bovina", category="Carne bovina"),
    TypeChange("Carne frango", name="Carne de frango", category="Carne de ave"),
    TypeChange("Peixe", category="Carne de peixe"),
    TypeChange("refrigerante", name="Refrigerante"),
    TypeChange("Queijo", name="Mussarela"),
    TypeChange("Extrato tomate", name="Extrato de tomate"),
    TypeChange("Pão", name="Pão francês"),
    # Grams to millilitres: the stored integers stay the same, 1 g reads 1 ml.
    TypeChange("Leite", base_unit="milliliter"),
]

# Emptied by the moves above. Deactivated, never deleted (decision 19).
DEACTIVATED_CATEGORIES = ["açogue"]


def q(value: str) -> str:
    return make_seed.sql_text(value)


def category_id(name: str) -> str:
    return (
        "(select id from public.category "
        f"where name_normalized = public.normalize_name({q(name)}))"
    )


def type_id(name: str) -> str:
    return (
        "(select id from public.product_type "
        f"where name_normalized = public.normalize_name({q(name)}))"
    )


def build() -> str:
    catalog = make_seed.read_catalog(make_seed.CATALOG)
    lines = [
        "-- GENERATED BY tool/import_catalog.py — do not edit by hand.",
        "-- Adds the catalog of supabase/seed_catalog.md to a database that already",
        "-- has real data. Deletes nothing; rerunning it changes nothing.",
        "",
        "begin;",
        "",
        "-- 1. Existing categories renamed to the catalog's names",
    ]
    for current, new in CATEGORY_RENAMES.items():
        lines.append(
            f"update public.category set name = {q(new)} "
            f"where name_normalized = public.normalize_name({q(current)});"
        )

    lines += ["", "-- 2. Catalog categories that do not exist yet"]
    for category in catalog:
        lines.append(
            f"insert into public.category (name) select {q(category)} "
            "where not exists (select 1 from public.category "
            f"where name_normalized = public.normalize_name({q(category)}));"
        )

    lines += ["", "-- 3. Existing types renamed, moved or re-united"]
    for change in TYPE_CHANGES:
        sets = []
        if change.name:
            sets.append(f"name = {q(change.name)}")
        if change.category:
            sets.append(f"category_id = {category_id(change.category)}")
        if change.base_unit:
            sets.append(f"base_unit = {q(change.base_unit)}")
        lines.append(
            f"update public.product_type set {', '.join(sets)} "
            f"where name_normalized = public.normalize_name({q(change.current)});"
        )
        if change.base_unit:
            # The leaves carry the magnitude too, and must match the type's.
            lines.append(
                f"update public.product set piece_size_unit = {q(change.base_unit)} "
                "where piece_size_unit is not null and product_registration_id in "
                "(select id from public.product_registration "
                f"where product_type_id = {type_id(change.name or change.current)});"
            )

    lines += ["", "-- 4. Categories emptied by the moves"]
    for category in DEACTIVATED_CATEGORIES:
        lines.append(
            "update public.category set active = false "
            f"where name_normalized = public.normalize_name({q(category)});"
        )

    lines += ["", "-- 5. Catalog types that do not exist yet"]
    for category, types in catalog.items():
        for catalog_type in types:
            lines.append(
                "insert into public.product_type (name, category_id, base_unit) "
                f"select {q(catalog_type.name)}, {category_id(category)}, "
                f"{q(catalog_type.base_unit)} where not exists (select 1 from "
                "public.product_type where name_normalized = "
                f"public.normalize_name({q(catalog_type.name)}));"
            )

    lines += [
        "",
        "-- 6. A type that already existed must speak the catalog's unit",
        "do $$",
        "declare mismatch text;",
        "begin",
        "  select string_agg(t.name || ' is ' || t.base_unit || ', catalog says ' || c.unit, '; ')",
        "    into mismatch",
        "    from public.product_type t",
        "    join (values",
    ]
    values = [
        f"      ({q(t.name)}, {q(t.base_unit)})"
        for types in catalog.values()
        for t in types
    ]
    lines.append(",\n".join(values))
    lines += [
        "    ) as c(name, unit) on t.name_normalized = public.normalize_name(c.name)",
        "   where t.base_unit <> c.unit;",
        "  if mismatch is not null then",
        "    raise exception 'unit mismatch: %', mismatch;",
        "  end if;",
        "end $$;",
        "",
        "-- 7. Generic brandless registrations, one leaf each: by weight with no",
        "--    packaging for Peso, Volume and Tamanho, 1 x 1 un for Contagem.",
    ]
    for types in catalog.values():
        for catalog_type in types:
            by_piece = catalog_type.base_unit == "unit"
            for description in catalog_type.descriptions or [""]:
                lines.append(
                    "with new_registration as (insert into public.product_registration "
                    "(product_type_id, description, selling_mode) "
                    f"select {type_id(catalog_type.name)}, {q(description)}, "
                    f"{q('by_piece' if by_piece else 'by_weight')} "
                    "where not exists (select 1 from public.product_registration "
                    f"where product_type_id = {type_id(catalog_type.name)} "
                    "and brand_id is null and description_normalized = "
                    f"public.normalize_name({q(description)})) returning id) "
                    + (
                        "insert into public.product (product_registration_id, "
                        "piece_count, piece_size, piece_size_unit, total_content) "
                        "select id, 1, 1, 'unit', 1 from new_registration;"
                        if by_piece
                        else "insert into public.product (product_registration_id) "
                        "select id from new_registration;"
                    )
                )

    lines += ["", "commit;", ""]
    return "\n".join(lines)


def main() -> None:
    OUTPUT.write_text(build(), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
